application: jmewipmonthlygallery
version: 1
runtime: php55
api_version: 1
default_expiration: "30d"

handlers:
- url: /(.*\.(css|less))
  http_headers:
    content_type: text/css
  static_files: \1
  upload: (.*\.(css|less))

- url: /(.*\.html)
  http_headers:
    content_type: text/html
  static_files: \1
  upload: (.*\.html)

- url: /(.*\.js)
  http_headers:
    content_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.ttf)
  http_headers:
    content_type: application/x-font-ttf
  static_files: \1
  upload: (.*\.ttf)    
    
- url: /(.*\.woff)
  http_headers:
    content_type: application/x-woff
  static_files: \1
  upload: (.*\.woff)  
    
- url: /(.*\.svg)
  http_headers:
    content_type: images/svg+xml
  static_files: \1
  upload: (.*\.(svg))

- url: /(.*\.(png))
  http_headers:
    content_type: image/png
  static_files: \1
  upload: (.*\.(png))
  
- url: /(.*\.txt)
  http_headers:
    content_type: text/plain
  static_files: \1
  upload: (.*\.txt) 
  
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html
  
- url: /(.+)
  static_files: \1/index.html
  upload: (.+)/index.html  
  
- url: /
  static_files: index.html
  upload: index.html
